include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_enum_constant_in_switch: error
  exclude:
    - lib/**/*.config.dart
    - lib/**/*.gr.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/**/*.graphql.dart
    - test/**/*.mocks.dart

linter:
  rules:
    always_use_package_imports: true
    sort_constructors_first: true
    sort_child_properties_last: true
    use_decorated_box: true
    avoid_redundant_argument_values: true
    always_put_required_named_parameters_first: true
    prefer_final_in_for_each: true
    unnecessary_await_in_return: true
    unawaited_futures: true
    await_only_futures: true
    use_super_parameters: true
    require_trailing_commas: true